// Copyright (C) Daft Software 2024, All Rights Reserved.
// Author: Sunny Blake-Webber

#pragma once

#include "NativeGameplayTags.h"

// Parent tag chat channel
FGCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_CHAT_CHANNEL);

// User Channels (Channels for player chat messages)
FGCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_CHAT_CHANNEL_ALL);
FGCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_CHAT_CHANNEL_TEAM);
FGCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_CHAT_CHANNEL_PARTY);
FGCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_CHAT_CHANNEL_WHISPER);

// System Channels (May be used for display system messages)
FGCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_CHAT_CHANNEL_INFO);
FGCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_CHAT_CHANNEL_WARNING);

// Player Modes aka building.
FGCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_PLAYER_MODES_BUILDING);
FGCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_PLAYER_MODES_ROTATEX);
FGCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_PLAYER_MODES_ROTATEY);
FGCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_PLAYER_MODES_ROTATEZ);

// Factory Commands.
FGCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_FACTORY_CMD_DELETE);
FGCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_FACTORY_CMD_SPAWN);

// Input
FGCORE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_INPUT_MOVE);
FGCORE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_INPUT_LOOK);
FGCORE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_INPUT_JUMP);
FGCORE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_INPUT_INTERACT);
FGCORE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_INPUT_CYCLE);
FGCORE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_INPUT_PRIMARYACTION);
FGCORE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_INPUT_SECONDARYACTION);

// Cheats
FGCORE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_CHEAT_GODMODE);
FGCORE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_CHEAT_UNLIMITEDHEALTH);

// Status
FGCORE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_STATUS_DAMAGEIMMUNITY);
FGCORE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_STATUS_DEATH);
FGCORE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_STATUS_DEATH_DYING);
FGCORE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_STATUS_DEATH_DEAD);

// Damages
FGCORE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GAMEPLAY_DAMAGE);
FGCORE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GAMEPLAY_DAMAGE_SELFDESTRUCT);
FGCORE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GAMEPLAY_DAMAGE_FELLOUTOFWORLD);

// Set by callers
FGCORE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_SETBYCALLER_DAMAGE);
FGCORE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_SETBYCALLER_HEAL);

// Abilities
FGCORE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ABILITY_BEHAVIOR_SURVIVESDEATH);


FGCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ITEM_ATTRIBUTE_EQUIPMENT);
FGCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ITEM_ATTRIBUTE_WEARABLE);

