// Copyright (C) Daft Software 2024, All Rights Reserved.
// Author: Sunny Blake-Webber

#include "FGGameplayTags.h"

UE_DEFINE_GAMEPLAY_TAG(TAG_CHAT_CHANNEL, "Chat.Channel");

UE_DEFINE_GAMEPLAY_TAG(TAG_CHAT_CHANNEL_ALL, "Chat.Channel.All");
UE_DEFINE_GAMEPLAY_TAG(TAG_CHAT_CHANNEL_TEAM, "Chat.Channel.Team");
UE_DEFINE_GAMEPLAY_TAG(TAG_CHAT_CHANNEL_PARTY, "Chat.Channel.Party");
UE_DEFINE_GAMEPLAY_TAG(TAG_CHAT_CHANNEL_WHISPER, "Chat.Channel.Whisper");

UE_DEFINE_GAMEPLAY_TAG(TAG_CHAT_CHANNEL_INFO, "Chat.Channel.Info");
UE_DEFINE_GAMEPLAY_TAG(TAG_CHAT_CHANNEL_WARNING, "Chat.Channel.Warning");

UE_DEFINE_GAMEPLAY_TAG(TAG_PLAYER_MODES_BUILDING, "Player.Modes.Building");

UE_DEFINE_GAMEPLAY_TAG(TAG_PLAYER_MODES_ROTATEX, "Player.Modes.RotateX");
UE_DEFINE_GAMEPLAY_TAG(TAG_PLAYER_MODES_ROTATEY, "Player.Modes.RotateY");
UE_DEFINE_GAMEPLAY_TAG(TAG_PLAYER_MODES_ROTATEZ, "Player.Modes.RotateZ");

UE_DEFINE_GAMEPLAY_TAG(TAG_FACTORY_CMD_DELETE, "Factory.Cmd.Delete");
UE_DEFINE_GAMEPLAY_TAG(TAG_FACTORY_CMD_SPAWN, "Factory.Cmd.Spawn");

UE_DEFINE_GAMEPLAY_TAG(TAG_INPUT_MOVE, "Input.Move");
UE_DEFINE_GAMEPLAY_TAG(TAG_INPUT_LOOK, "Input.Look");
UE_DEFINE_GAMEPLAY_TAG(TAG_INPUT_JUMP, "Input.Jump");
UE_DEFINE_GAMEPLAY_TAG(TAG_INPUT_INTERACT, "Input.Interact");
UE_DEFINE_GAMEPLAY_TAG(TAG_INPUT_CYCLE, "Input.Cycle");
UE_DEFINE_GAMEPLAY_TAG(TAG_INPUT_PRIMARYACTION, "Input.PrimaryAction");
UE_DEFINE_GAMEPLAY_TAG(TAG_INPUT_SECONDARYACTION, "Input.SecondaryAction");

UE_DEFINE_GAMEPLAY_TAG(TAG_CHEAT_GODMODE, "Cheat.GodMode");
UE_DEFINE_GAMEPLAY_TAG(TAG_CHEAT_UNLIMITEDHEALTH, "Cheat.UnlimitedHealth");

UE_DEFINE_GAMEPLAY_TAG(TAG_STATUS_DAMAGEIMMUNITY, "Status.DamageImmunity");
UE_DEFINE_GAMEPLAY_TAG(TAG_STATUS_DEATH, "Status.Death");
UE_DEFINE_GAMEPLAY_TAG(TAG_STATUS_DEATH_DYING, "Status.Death.Dying");
UE_DEFINE_GAMEPLAY_TAG(TAG_STATUS_DEATH_DEAD, "Status.Death.Dead");

UE_DEFINE_GAMEPLAY_TAG(TAG_GAMEPLAY_DAMAGE, "Gameplay.Damage");
UE_DEFINE_GAMEPLAY_TAG(TAG_GAMEPLAY_DAMAGE_SELFDESTRUCT, "Gameplay.Damage.SelfDestruct");
UE_DEFINE_GAMEPLAY_TAG(TAG_GAMEPLAY_DAMAGE_FELLOUTOFWORLD, "Gameplay.Damage.FellOutOfWorld");

UE_DEFINE_GAMEPLAY_TAG(TAG_SETBYCALLER_DAMAGE, "SetByCaller.Damage");
UE_DEFINE_GAMEPLAY_TAG(TAG_SETBYCALLER_HEAL, "SetByCaller.Heal");

UE_DEFINE_GAMEPLAY_TAG(TAG_ABILITY_BEHAVIOR_SURVIVESDEATH, "Ability.Behavior.SurvivesDeath");

UE_DEFINE_GAMEPLAY_TAG(TAG_ITEM_ATTRIBUTE_EQUIPMENT, "Item.Attribute.Equipment");
UE_DEFINE_GAMEPLAY_TAG(TAG_ITEM_ATTRIBUTE_WEARABLE, "Item.Attribute.Wearable");

